[package]
name = "day1"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }

[[bin]]
name = "day1_part1"
path = "src/part1.rs"

[[bin]]
name = "day1_part2"
path = "src/part2.rs"
